server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false  # Disable default Hibernate logging
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.SQL: debug  # Log SQL queries
    # org.hibernate.orm.jdbc.bind: trace  # Log SQL parameters
    # org.hibernate.type.descriptor.sql: trace  # Log SQL parameters details
